### ISSUE TITLE
IOS does not display banner ads after Navigate to a new screen

### ISSUE THREAD

**Issue by elkad** [YoussefKababe/admob_flutter#35]
Hi. I have used admob which is recent ios version. i have got problem in displaying banner when i navigated from main page to a new screen. ( it is correctly working to display in main page)
could you please check this out?

**Comment by theneshofficial** [comment]
Facing the same issue, below is my error log

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(create_failed, can't create a view on a headless engine, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:132)
<asynchronous suspension>
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:454)
<asynchronous suspension>
#4      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:404)
#5      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:414)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3862)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2764)
#10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2764)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722)
#16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2764)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#23     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601)
#24     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#32     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#36     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#44     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#48     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#54     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1034)
#55     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:984)
#56     _GrowableList.forEach (dart:core-patch/growable_array.dart:278)
#57     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:995)
#58     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:961)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#62     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601)
#63     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992)
#64     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#70     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#76     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#82     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#88     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#92     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#96     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#98     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#100    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#106    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#110    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#114    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#122    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#126    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#130    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#132    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1034)
#133    SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:984)
#134    _GrowableList.forEach (dart:core-patch/growable_array.dart:278)
#135    SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:995)
#136    SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:961)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#138    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601)
#139    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992)
#140    _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#142    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#144    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#146    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#148    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#152    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#154    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#158    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#160    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#164    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#168    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#171    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#172    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#176    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#178    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#180    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601)
#181    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992)
#182    _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#184    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#186    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#188    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#190    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#191    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#194    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#196    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#197    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#199    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#200    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#202    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#205    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#206    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#207    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#209    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#210    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#211    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#214    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#215    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#217    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#218    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#221    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#222    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#226    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#229    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#230    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#232    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601)
#233    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#236    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#237    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#238    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#239    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#241    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#242    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#243    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#244    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#245    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#246    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#247    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#248    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#250    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#251    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#252    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#253    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#254    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#256    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#257    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#258    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#259    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#260    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#261    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#262    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#263    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#264    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#265    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#266    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#267    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#268    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#269    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#270    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#271    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#272    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#273    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#274    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#275    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#276    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#277    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#278    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#279    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#280    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#281    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#282    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#283    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#284    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#285    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#286    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#287    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#288    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#289    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#290    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#291    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#292    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#293    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#294    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#295    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#296    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#297    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#298    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#299    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#300    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#301    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#302    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#303    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#304    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#305    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#306    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#307    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#308    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#309    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#310    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#311    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#312    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#313    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601)
#314    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992)
#315    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#316    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#317    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#318    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#319    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#320    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#321    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#322    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#323    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#324    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#325    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#326    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#327    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#328    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#329    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#330    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#331    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#332    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#333    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#334    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#335    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#336    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#337    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#338    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#339    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#340    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#341    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#342    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#343    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#344    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#345    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#346    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#347    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#348    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#349    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#350    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#351    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#352    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#353    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#354    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#355    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#356    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
#357    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#358    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#359    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#360    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
#361    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#362    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
#363    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#364    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#365    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#366    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
#367    Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
#368    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
#369    Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
#370    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278)
#371    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700)
#372    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286)
#373    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012)
#374    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952)
#375    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864)
#376    _rootRun (dart:async/zone.dart:1124)
#377    _CustomZone.run (dart:async/zone.dart:1021)
#378    _CustomZone.runGuarded (dart:async/zone.dart:923)
#379    _invoke (dart:ui/hooks.dart:219)
#380    _drawFrame (dart:ui/hooks.dart:178)
```

**Comment by kmcgill88** [comment]
Hard to tell what is causing this from the stack trace. I don't have time to debug this right now. If anyone does I'd suggest launching the `example` app from Xcode and see if something is crashing on the Swift side or Dart side.
