### ISSUE TITLE
Error build for iOS

### ISSUE THREAD

**Issue by matte5031** [YoussefKababe/admob_flutter#43]
Hello!

I have been trying to build for iOS this whole day without success unfortunately. 
Tried both the stable and beta channel. 
The error I get is the below:

The Swift pod `admob_flutter` depends upon `FirebaseCore`, `FirebaseInstanceID`, `GoogleUtilities`, and `nanopb`, which do not define modules.
    To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set
    `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:135:in
    `verify_swift_pods_have_module_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:415:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:118:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/bin/pod:22:in `<main>'

I have tried the other firebase_admob plugin and get no issues when building with it.
When I add use_modular_headers! or use_frameworks! inside the Podfile the build goes a little bit further but still fails later. Am I supposed to have use_frameworks! or something in the podfile or not in order to use this plugin?

Does anyone have anyone know what might be causing this issue, any help or input at all is very much apprecited, thanks!

/Mattias

**Adding my current podfile below incase it can help:**
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

pod 'Firebase/Core'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  #use_modular_headers!
  #use_frameworks!
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**And my pubspec.yaml dependencies incase it can help**
dependencies:
  flutter:
    sdk: flutter
  css_colors: ^1.0.2
  http: ^0.12.0+2
  path_provider: ^1.1.0
  firebase_messaging: ^5.0.2
  firebase_core: ^0.4.0+5
  firebase_database: ^3.0.2
  shared_preferences: ^0.5.3+1
  device_info: ^0.4.0+1
  uuid: ^2.0.0
  camera: ^0.5.0
  flutter_secure_storage: ^3.2.1+1
  flutter_native_image: ^0.0.4
  flutter_staggered_grid_view: ^0.2.7
  connectivity: ^0.4.3+1
  flushbar: ^1.7.0
  launch_review: ^2.0.0
  admob_flutter: ^0.3.1

**Comment by ejprok** [comment]
I'm getting the same issue as well

**Comment by duduf15** [comment]
Hi, same for me, no one found a workaround ?
May we disable the plugin for the iOS platform ?
