### ISSUE TITLE
The Swift pod `admob_flutter` depends upon `FirebaseCore`

### ISSUE THREAD

**Issue by jiharal** [YoussefKababe/admob_flutter#53]
~~~ 
   -> Using url_launcher (0.0.1)
      - Running pre install hooks
    [!] The following Swift pods cannot yet be integrated as static libraries:

    The Swift pod `admob_flutter` depends upon `FirebaseCore`, `FirebaseInstanceID`, `GoogleUtilities`, and `nanopb`, which do not define modules. To opt into those targets generating module maps (which
    is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular
    dependencies.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:135:in `verify_swift_pods_have_module_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:415:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:118:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone X.
~~~

**Comment by BPHvZ** [comment]
Maybe add this to your pubspec.yaml https://pub.dev/packages/firebase_core

**Comment by kmcgill88** [comment]
@jiharal Have you resolved this issue?
