### ISSUE TITLE
Getting this error when moving from one screen to another

### ISSUE THREAD

**Issue by abinmittu** [YoussefKababe/admob_flutter#58]
E/flutter ( 6007): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method dispose on channel admob_flutter/banner_8)
E/flutter ( 6007): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter ( 6007): <asynchronous suspension>
E/flutter ( 6007): #1      AdmobBannerController.dispose (package:admob_flutter/src/admob_banner_controller.dart:17:14)
E/flutter ( 6007): #2      _AdmobBannerState.dispose (package:admob_flutter/src/admob_banner.dart:68:17)
E/flutter ( 6007): #3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4107:12)
E/flutter ( 6007): #4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1737:13)
E/flutter ( 6007): #5      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1735:7)
E/flutter ( 6007): #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
E/flutter ( 6007): #7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1733:13)
E/flutter ( 6007): #8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1735:7)
E/flutter ( 6007): #9      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5080:14)
E/flutter ( 6007): #10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1733:13)
E/flutter ( 6007): #11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1735:7)
E/flutter ( 6007): #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
E/flutter ( 6007): #13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1733:13)
E/flutter ( 6007): #14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1735:7)
E/flutter ( 6007): #15     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5181:16)
E/flutter ( 6007): #16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1733:13)
E/flutter ( 6007): #17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1735:7)
E/flutter ( 6007): #18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5080:14)
E/flutter ( 6007): #19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1733:13)
E/flutter ( 6007): #20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1735:7)
E/flutter ( 6007): #21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
E/flutter ( 6007): #22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1733:13)
E/flutter ( 6007): #23     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
E/flutter ( 6007): #24     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1746:25)
E/flutter ( 6007): #25     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2426:27)
E/flutter ( 6007): #26     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2258:15)
E/flutter ( 6007): #27     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2425:7)
E/flutter ( 6007): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:18)
E/flutter ( 6007): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
E/flutter ( 6007): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
E/flutter ( 6007): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
E/flutter ( 6007): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
E/flutter ( 6007): #33     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6007): #34     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6007): #35     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6007): #36     _invoke (dart:ui/hooks.dart:236:10)
E/flutter ( 6007): #37     _drawFrame (dart:ui/hooks.dart:194:3)
E/flutter ( 6007):

**Comment by kmcgill88** [comment]
Can you add more context to this, please? iOS, Android, both? Flutter doctor info.

**Comment by kmcgill88** [comment]
@abinmittu [this idea](https://github.com/YoussefKababe/admob_flutter/issues/61#issuecomment-520670535) might interest you too.
