### ISSUE TITLE
(Android) : Unhandled Exception: PlatformException(error, Trying to create a platform view of unregistered type: admob_flutter/banner, null)

### ISSUE THREAD

**Issue by zukinaru** [YoussefKababe/admob_flutter#69]
I got below error when trying admob_flutter, the ads itself not loading/showing.

```
09-24 10:07:54.584 11992 12066 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Trying to create a platform view of unregistered type: admob_flutter/banner, null)
09-24 10:07:54.584 11992 12066 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
09-24 10:07:54.584 11992 12066 E flutter : #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316)
09-24 10:07:54.584 11992 12066 E flutter : <asynchronous suspension>
09-24 10:07:54.584 11992 12066 E flutter : #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640)
09-24 10:07:54.584 11992 12066 E flutter : <asynchronous suspension>
09-24 10:07:54.584 11992 12066 E flutter : #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557)
09-24 10:07:54.584 11992 12066 E flutter : <asynchronous suspension>
09-24 10:07:54.584 11992 12066 E flutter : #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174)
09-24 10:07:54.584 11992 12066 E flutter : <asynchronous suspension>
09-24 10:07:54.584 11992 12066 E flutter : #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155)
09-24 10:07:54.584 11992 12066 E flutter : #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1686)
09-24 10:07:54.584 11992 12066 E flutter : #7      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259)
09-24 10:07:54.584 11992 12066 E flutter : #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259)
09-24 10:07:54.584 11992 12066 E flutter : #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #11     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744)
09-24 10:07:54.584 11992 12066 E flutter : #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #17     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:205)
09-24 10:07:54.584 11992 12066 E flutter : #18     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238)
09-24 10:07:54.584 11992 12066 E flutter : #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #20     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181)
09-24 10:07:54.584 11992 12066 E flutter : #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406)
09-24 10:07:54.584 11992 12066 E flutter : #23     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1681)
09-24 10:07:54.584 11992 12066 E flutter : #24     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1644)
09-24 10:07:54.584 11992 12066 E flutter : #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1701)
09-24 10:07:54.584 11992 12066 E flutter : #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
09-24 10:07:54.584 11992 12066 E flutter : #43     RenderObjec
```

any idea?

Thank You

**Comment by jqmcrvlh** [comment]
Try to restart your project.  I received this error a feel minutes ago. Then I decide to close it and open an old project with the same method to AdMob and  I saw that old project works.   Then I returned to the project with error and started again, and that error message disappeared.

**Comment by zukinaru** [comment]
> Try to restart your project. I received this error a feel minutes ago. Then I decide to close it and open an old project with the same method to AdMob and I saw that old project works. Then I returned to the project with error and started again, and that error message disappeared.

I build my project using codemagic.io because my laptop will noisy & hot when perform build operation.

Any Idea ?

**Comment by jqmcrvlh** [comment]
I am sorry I have no idea, I do not use codemagic.io  in my tests, I do not know how it works.  
My last suggestions are to try to check if your Android / iOS app id, generated by Admob, are in the right places in AndroidManifest.xml and iOS Info.plis.   Check if getAppId() contains a right app id for Android and iOS and getBannerAdUnitId() shows the right code of advert for Android and iOS from Admob web site.  And, as last resort, try to create new apps code in Admob portal and replace the old ones.
