### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel admob_flutter)

### ISSUE THREAD

**Issue by zukinaru** [YoussefKababe/admob_flutter#72]
I never cant show admob banner on my flutter apps, instead i got below error:

```
E/flutter (11438): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel admob_flutter)
E/flutter (11438): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (11438): <asynchronous suspension>
E/flutter (11438): #1      new Admob.initialize (package:admob_flutter/src/admob.dart:6:14)
E/flutter (11438): #2      _HomeScreenState.initState (package:prj789apps/src/ui/home/home_screen.dart:91:13)
E/flutter (11438): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter (11438): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (11438): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (11438): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (11438): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (11438): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (11438): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (11438): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (11438): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (11438): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (11438): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (11438): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (11438): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (11438): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (11438): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (11438): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (11438): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (11438): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (11438): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (11438): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (11438): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (11438): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (11438): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (11438): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (11438): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (11438): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (11438): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (11438): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (11438): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter (11438): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (11438): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (11438): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (11438): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (11438): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (11438): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (11438): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (11438): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (11438): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (11438): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (11438): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (11438): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (11438): #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter (11438): #45     Compone
```

any idea to solve ?

Thanks in Advance...

**Comment by camposFabio** [comment]
Same error here (Arch Linux, 

Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (6 days ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

Pubspec.yaml
  admob_flutter: ^0.3.4

main:
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:admob_flutter/admob_flutter.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize without device test ids
  Admob.initialize('ca-app-pub-3940256099942544/6300978111');
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  String getBannerAdUnitId() {
    if (Platform.isIOS) {
      return 'ca-app-pub-3940256099942544~1458002511';
    } else if (Platform.isAndroid) {
      return 'ca-app-pub-3940256099942544~3347511713';
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            AdmobBanner(
              adUnitId: getBannerAdUnitId(),
              adSize: AdmobBannerSize.BANNER,
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

--------------------------------------------------------------------------------------------------------------------------------------------------------
2020-07-06 20:49:33.897 3934-3955/br.com.camposfabio.teste_admob E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel admob_flutter)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #2      new Admob.initialize (package:admob_flutter/src/admob.dart:6:14)
    #3      main (package:teste_admob/main.dart:9:9)
    #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
    #5      _rootRun (dart:async/zone.dart:1184:13)
    #6      _CustomZone.run (dart:async/zone.dart:1077:19)
    #7      _runZoned (dart:async/zone.dart:1619:10)
    #8      runZonedGuarded (dart:async/zone.dart:1608:12)
    #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
    #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
    #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
2020-07-06 20:54:41.748 3934-3955/br.com.camposfabio.teste_admob E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel admob_flutter)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #2      new Admob.initialize (package:admob_flutter/src/admob.dart:6:14)
    #3      main (package:teste_admob/main.dart:9:9)
    #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
    #5      _rootRun (dart:async/zone.dart:1184:13)
    #6      _CustomZone.run (dart:async/zone.dart:1077:19)
    #7      _runZoned (dart:async/zone.dart:1619:10)
    #8      runZonedGuarded (dart:async/zone.dart:1608:12)
    #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
    #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
    #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
2020-07-06 20:55:32.638 3934-3955/br.com.camposfabio.teste_admob E/flutter: [ERROR:flutter/shell/common/shell.cc(213)] Dart Error: Unhandled exception:
    PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: admob_flutter/banner
        at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:97)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:95)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
    , null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:633:54)
    #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:550:14)
    #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
    #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
    #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
    #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #10     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:266:13)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #12     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:746:15)
    #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #14     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:394:13)
    #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #16     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
    #17     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
    #18     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
    #19     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
    #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #24     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1248:11)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #30     RenderProxyBoxMixin.performLayout (

**Comment by JeetBhattachariya** [comment]
did you solve this issue ? I am getting the exact same error .

**Comment by rafagan** [comment]
up

**Comment by larsien** [comment]
how to fix this?
